# config.py
DEFAULT_SIMULATION_STEPS = 50
VEHICLE_ARRIVAL_PROBABILITY = 0.35
EMERGENCY_PROBABILITY = 0.05
NORMAL_VEHICLES_PER_STEP = 2
EMERGENCY_VEHICLES_PER_STEP = 1
FIXED_SIGNAL_DURATION = 5
MIN_GREEN_TIME = 3
MAX_GREEN_TIME = 8
RANDOM_SEED = 42
